spring:
  datasource:
    username: demo
    password: demo
    url: jdbc:mysql://localhost:3306/infygo_creditcard
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  servlet.context-path: /api
  port: 9300
  
  
#logging:
#  file:
#    name: Errorlog.log
#  level:
#    root: info
#    com.infoys.irs: info
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"
