spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: creditCardMS
        uri: lb://creditcardMS
        predicates:
        - Path=/payment
        filters:
        - PrefixPath=/api
      - id: flightMS
        uri: lb://flightMS
        predicates:
        - Path=/api/flights/**
      - id: passengerMS
        uri: lb://passengerMS
        predicates:
        - Path=/api/book/**
      - id: ticketMS
        uri: lb://ticketMS
        predicates:
        - Path=/api/ticket
      - id: userMS
        uri: lb://userMS
        predicates:
        - Path=/api/login,/api/register